server:
  port: 21200

spring:
  application:
    name: admin-server
  cloud:
    consul:
      host: localhost
      port: 8500
  security:
    user:
      name: admin
      password: 123456
  boot:
    admin:
      discovery:
        ignored-services: consul, admin-server

logging:
  level:
    root: warn
    com.yupaits: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always