server:
  port: 21200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:21100/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: admin-server
  boot:
    admin:
      client:
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
        instance:
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
  security:
    user:
      name: admin
      password: 123456

logging:
  level:
    root: warn
    com.yupaits: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always