server:
  port: 20000

spring:
  application:
    name: gateway-server
  cloud:
    consul:
      host: localhost
      port: 8500
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: warn
    com.yupaits: info
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always