server:
  port: 23100

spring:
  application:
    name: shop-server
  cloud:
    consul:
      host: localhost
      port: 8500
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    sender:
      type: RABBIT
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

security:
  oauth2:
    resource:
      id: shop-server
      user-info-uri: http://localhost:22000/auth/user
      prefer-token-info: false

ribbon:
  eager-load:
    enabled: true
    clients: service-shop, service-order

logging:
  level:
    root: warn
    com.yupaits: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always